### ISSUE TITLE
如何在序号后面著录引用页码

### ISSUE THREAD

**Issue by happyTonakai** [CTeX-org/gbt7714-bibtex-style#55]
## 编译环境
宏包版本：gbt7714 v1.0
标注样式：super

## 描述问题
国标第 14 页要求，多次引用同一文献，在序号的 “[ ]” 外著录引用页码，请问这个应该怎么实现？
我试了用 `\cite[\textsuperscript{216}]{knuth86a}` 但是方括号后面跟了一个空格，与国标中有所不同。

bib 数据库代码：
```TeX
@book{knuth86a,
  author    = {Donald E. Knuth},
  title     = {The {\TeX}book},
  volume    = {A},
  publisher = {Addison-Wesley},
  address   = {Reading, MA, USA},
  year      = {1986},
  series    = {Computers and Typesetting},
}
```

截图：
<img width="102" alt="批注 2020-04-29 173204" src="https://user-images.githubusercontent.com/21305646/80581256-7cd30b80-8a3f-11ea-9399-182348ba4b35.png">

**Comment by hushidong** [comment]
去掉superscript命令试试？ hzzmail 邮箱：hzzmail@sjtu.org 签名由 网易邮箱大师 定制 在2020年04月29日 17:34，Tonakai 写道： 编译环境 宏包版本：gbt7714 v1.0 标注样式：super 描述问题 国标第 14 页要求，多次引用同一文献，在序号的 “[ ]” 外著录引用页码，请问这个应该怎么实现？ 我试了用 \cite[\textsuperscript{216}]{knuth86a} 但是方括号后面跟了一个空格，与国标中有所不同。 bib 数据库代码： @book{knuth86a,

  author    = {Donald E. Knuth},

  title     = {The {\TeX}book},

  volume    = {A},

  publisher = {Addison-Wesley},

  address   = {Reading, MA, USA},

  year      = {1986},

  series    = {Computers and Typesetting},

} 截图： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by happyTonakai** [comment]
去掉的话是正文大小

**Comment by hushidong** [comment]
用citet或citep命令试试？

**Comment by zepinglee** [comment]
> ## 编译环境
> 宏包版本：gbt7714 v1.0
> 标注样式：super
> 
> ## 描述问题
> 国标第 14 页要求，多次引用同一文献，在序号的 “[ ]” 外著录引用页码，请问这个应该怎么实现？
> 我试了用 `\cite[\textsuperscript{216}]{knuth86a}` 但是方括号后面跟了一个空格，与国标中有所不同。
> 
> bib 数据库代码：
> 
> ```
> @book{knuth86a,
>   author    = {Donald E. Knuth},
>   title     = {The {\TeX}book},
>   volume    = {A},
>   publisher = {Addison-Wesley},
>   address   = {Reading, MA, USA},
>   year      = {1986},
>   series    = {Computers and Typesetting},
> }
> ```
> 
> 截图：
> <img alt="批注 2020-04-29 173204" width="102" src="https://user-images.githubusercontent.com/21305646/80581256-7cd30b80-8a3f-11ea-9399-182348ba4b35.png">

引用样式的设置需要调用 gbt7714.sty，然后只需要 `\cite[216]{knuth86a}` 就可以了。

另外建议用最新版

**Comment by happyTonakai** [comment]
已解决，感谢！
